/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapgenerator;

import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author jonathan.guerne
 */
public class PanLayerButotn extends javax.swing.JPanel {

    /**
     * Creates new form PanLayerButotn
     */
    public PanLayerButotn() {
        initComponents();
    }

    public void test() {
        this.setLayout(new GridLayout(3, 3));
        this.add(new JButton("NW"));
        this.add(new JButton("N"));
        this.add(new JButton("NE"));
        this.add(new JButton("W"));
        this.add(new JButton(" "));
        this.add(new JButton("E"));
        this.add(new JButton("SW"));
        this.add(new JButton("S"));
        this.add(new JButton("SE"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
